version: "3.7"

services:
  mongo4-1:
    image: mongo:4.0
    command: ["mongod", "--replSet", "rs"]
    networks:
      - mongo4-net
    volumes:
      - mongo4-data-1:/data/db
      - mongo4-config-1:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.manager == YOUR_MANAGER_LABEL

  mongo4-2:
    image: mongo:4.0
    command: ["mongod", "--replSet", "rs"]
    networks:
      - mongo4-net
    volumes:
      - mongo4-data-2:/data/db
      - mongo4-config-2:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints:
          - node.labels.worker == YOUR_WORKER_LABEL_1

  mongo4-3:
    image: mongo:4.0
    command: ["mongod", "--replSet", "rs"]
    networks:
      - mongo4-net
    volumes:
      - mongo4-data-3:/data/db
      - mongo4-config-3:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints:
          - node.labels.worker == YOUR_WORKER_LABEL_2

networks:
  mongo4-net:
    external: true

volumes:
  mongo4-data-1:
  mongo4-config-1:
  mongo4-data-2:
  mongo4-config-2:
  mongo4-data-3:
  mongo4-config-3:
